### ISSUE TITLE
Testing new databases

### ISSUE THREAD

**Issue by halexand** [AlexanderLabWHOI/EUKulele#2]
Hurrah! The tax-assignment code is running faster and all seems to be well (thanks to @akrinos in PR#1). 

I think our next big step is testing it out with new databases beyond this MMETSP build. 

A few that I think we should checkout: 

- [x] MarineRefII: http://roseobase.org/data/ (which I think includes phylodb)
- [x] PhyloDB: https://github.com/allenlab/PhyloDB

... and others? @akrinos @shu251 @cnatalie

**Comment by cnatalie** [comment]
- [ ] MetaProt: https://github.com/williamorsi/MetaProt-database
- [ ] EukZoo: https://zenodo.org/record/1476236#.Xu-8wZNKgnU

**Comment by halexand** [comment]
- [ ] EukProt: https://doi.org/10.6084/m9.figshare.12417881.v2 (looks to have good coverage of metazoa!)

**Comment by halexand** [comment]
@akrinos I think we should prioritize EUKProt next for testing.

**Comment by akrinos** [comment]
> @akrinos I think we should prioritize EUKProt next for testing.

More to queue over the long weekend.
