### ISSUE TITLE
Conda installation fails

### ISSUE THREAD

**Issue by johanneswerner** [AlexanderLabWHOI/EUKulele#24]
Hello, 

I am trying to install EUKulele as described in the  [documentation](https://eukulele.readthedocs.io/en/latest/quickstart.html#installation) and I am getting the following error: 

```
$ conda install -c akrinos -c bioconda -c conda-forge EUKulele
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

I am using a freshly deployed Ubuntu 20.04.1 LTS with conda v. 4.8.3. 

Did anyone else have the problem or can reproduce it?

**Comment by will-rowe** [comment]
Hi @johanneswerner . I ran into the same difficulty but think it is because the documentation needs the conda instructions fixing.

In the docs you have:

```
conda create -n EUKulele
conda install -c akrinos -c bioconda -c conda-forge EUKulele
conda activate EUKulele
```

When it should be something like:

```
conda create -n EUKulele
conda activate EUKulele
conda install -c akrinos -c bioconda -c conda-forge EUKulele
```

The current instructions will install the software into the current env, where you may have conflicts etc., and then activate the EUKulele environment. The proposed fix activates a clean environment to use for EUKulele before installing the software. This fixes the issue for me.

As an aside - [mamba](https://github.com/mamba-org/mamba), the drop in conda replacement, massively speeds up the installation for me.

**Comment by jcmcnch** [comment]
@akrinos, this still seems to be an issue. I can't install - getting same error as Johannes with both conda and mamba.

conda error:

```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
Note that strict channel priority may have removed packages required for satisfiability.
```

mamba error:
```
Looking for: ['eukulele']

akrinos/linux-64         [====================] (00m:00s) Done
akrinos/noarch           [====================] (00m:00s) Done
ursky/linux-64           [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:01s) Done
ursky/noarch             [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:03s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
bioconda/linux-64        [====================] (00m:04s) Done
conda-forge/noarch       [====================] (00m:04s) Done
pkgs/main/linux-64       [====================] (00m:04s) Done
pkgs/r/linux-64          [====================] (00m:04s) Done
conda-forge/linux-64     [====================] (00m:15s) Done
Encountered problems while solving.
Problem: package eukulele-0.0.1-pyh39e3cac_0 requires argparse, but none of the providers can be installed
```

**Comment by johanneswerner** [comment]
@jcmcnch 

Good morning, 

I have an idea what could have caused this error. Could you share your bash commands for setting up the environment? I would like to test if I could reproduce it.

**Comment by akrinos** [comment]
Hi @jcmcnch, thanks for bringing this up. I don't see too many issues referencing the error online, though it's coming from Linux. I also note here that the current `EUKulele` version is 1.0.1 and `mamba` appears to be attempting to install 0.0.1, so I might try specifying the version explicitly. I usually also try removing strict channel priority via `conda config --describe channel_priority flexible`. Thank you @johanneswerner for helping with this! Hopefully we can reproduce and fix the problem.

**Comment by jcmcnch** [comment]
@johanneswerner , I followed the install commands listed on readthedocs and referenced above. 

```
 conda create -n EUKulele
 conda activate EUKulele
 conda install -c akrinos -c bioconda -c conda-forge EUKulele
```

@akrinos , tried making my conda flexible by using the following command that seems to be equivalent to what you're suggesting above (since the command you provided gave me an error): `conda config --set channel_priority true`

Unfortunately, this resulted in conda not being able to solve the environment - it ran for some ~4 hours without coming to a solution before I cancelled the job.

mamba also fails `mamba install -c akrinos -c bioconda -c conda-forge EUKulele==1.0.1` after changing channel priority with the following error:

```
Looking for: ['eukulele 1.0.1', 'python 3.6.0']

0 packages in https://conda.anaconda.org/akrinos/linux-64
3 packages in https://conda.anaconda.org/akrinos/noarch
33639 packages in https://conda.anaconda.org/bioconda/linux-64
21311 packages in https://conda.anaconda.org/bioconda/noarch
142297 packages in https://conda.anaconda.org/conda-forge/linux-64
43890 packages in https://conda.anaconda.org/conda-forge/noarch
18883 packages in https://repo.anaconda.com/pkgs/main/linux-64
2444 packages in https://repo.anaconda.com/pkgs/main/noarch
6637 packages in https://repo.anaconda.com/pkgs/r/linux-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
47 packages in https://conda.anaconda.org/ursky/linux-64
0 packages in https://conda.anaconda.org/ursky/noarch
Encountered problems while solving.
Problem: package eukulele-1.0.1-pyh39e3cac_0 requires busco 4.0.6, but none of the providers can be installed
```

BUT, the good news is in the end updating conda did the trick, now it installs without issues. I suggest updating the install instructions to incorporate this and to use mamba as well, e.g.:

```
conda update -n base conda
conda create -n EUKulele
conda activate EUKulele
conda install -c conda-forge mamba
mamba install -c akrinos -c bioconda -c conda-forge EUKulele==1.0.1
```

**Comment by akrinos** [comment]
Oops, looks like I provided the wrong command @jcmcnch, sorry about that! 

Very interesting that updating `conda` changed that! The information that I found about the `mamba` error did all seem to point to something OS-related, but I really don't know why updating would have that effect. Maybe others have better insight!

**Comment by johanneswerner** [comment]
Fascinating. Is the installation issue solved for now or should we look deeper into it?

**Comment by jcmcnch** [comment]
@johanneswerner it's solved at least from my end. Things are working well now and I'm proceeding with test-driving the software.
