### ISSUE TITLE
Question: Threads and estimated runtime

### ISSUE THREAD

**Issue by susheelbhanu** [AlexanderLabWHOI/EUKulele#33]
Hi, 

Thank you for a very nice and timely tool. Given that I have to run a few samples, I have two questions. 

1. I was wondering if there was an option to speed up the process by specifying `threads` or `parallelisation`. Sorry if I missed it in the documentation. Is this an option?
2. I need to run this on a `HPC`, so for a collection of MAGs (eg. n=10) - would you happen to know the `runtime`?

Thanks a lot for your help with this!
-Susheel

**Comment by akrinos** [comment]
Hi @susheelbhanu, thanks so much for the comments! At this time, `EUKulele` runs on a single machine, so a single node on the HPC, but takes advantage of the resources available to it on that node. It will detect this and run in parallel according to the amount of memory on the machine. In the future, we will add the option to accommodate for some problems we have had with memory requirements for very large files. 

As for your second question, it really depends more so on the size of the files, and the amount of memory you have available on the machine - could you give me an estimate of the maximum size of the FASTA files and the amount of memory you have available on your HPC system? Thanks!

**Comment by susheelbhanu** [comment]
Thank you @akrinos.

I'm talking an average size of `866M` per fasta file on a 32G machine.

**Comment by susheelbhanu** [comment]
FYI. Running 21 metagenomes, each with an average 700Mb file, on a HPC with `24 cpus, 4GB/cpu` had the following runtime: `~ 38 hours`
```
Fri Feb 19 06:53:11 CET 2021
Running EUKulele with command line arguments, as no valid configuration file was provided.
....
....
EUKulele run complete!
Sat Feb 20 19:09:28 CET 2021
