### ISSUE TITLE
Conda installation issue

### ISSUE THREAD

**Issue by susheelbhanu** [AlexanderLabWHOI/EUKulele#34]
Hi again.. 

I'm having trouble installing the tool via `conda`. As noted in one of the earlier issues, I updated conda and still the problems persists. 

```
conda activate eukulele
conda install -c akrinos -c bioconda -c conda-forge EUKulele
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - Bus error
```

I tried it on a different `high-mem` machine and it's been `~11 hours` and the environment is still being solved
```
conda activate eukulele
conda install -c bioconda eukulele
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
```

Any suggestions on how to speed up the process? Thank you!

**Comment by akrinos** [comment]
Hi @susheelbhanu! For the `conda` installation, I would suggest removing `-c akrinos`. `EUKulele` is now available on `bioconda`, which speeds up the installation! If it still doesn't work on your machine, though, the `pip` install might be the way to go for you, given your `conda` setup. Thanks for the queries!

**Comment by susheelbhanu** [comment]
Will give it a go - thank you!

**Comment by susheelbhanu** [comment]
@akrinos Just thought I'd leave this here for future reference. The `pip installation` worked. 

So, I exported the environment file. It's attached here. Hope it helps someone who may run into this. Had to rename it to `.txt` from `.yaml` so I could upload. ;) 
[eukulele.txt](https://github.com/AlexanderLabWHOI/EUKulele/files/6002675/eukulele.txt)

**Comment by akrinos** [comment]
Thanks for that @susheelbhanu ! But note that if you do use the `pip` installation, you will need a few other tools installed separately as well, which is the downside of that approach (but it tends to solve faster than `conda`). Those dependencies are [here](https://eukulele.readthedocs.io/en/latest/install.html), and should be sorted with `conda install -c bioconda -c conda-forge blast busco=4.0.6 diamond transdecoder` via `conda` (though newer `BUSCO` should now work and the docs should be updated). Happy to help if anything goes wrong with the dependencies!

**Comment by susheelbhanu** [comment]
Thank you! I suppose one could update the environment file with the dependencies too.. Thanks again for the help!
