### ISSUE TITLE
Update documentation with default nucleotide extension

### ISSUE THREAD

**Issue by cnatalie** [AlexanderLabWHOI/EUKulele#45]
Uses .fasta by default, not .fna

https://eukulele.readthedocs.io/en/latest/running-eukulele.html

**Comment by akrinos** [comment]
https://github.com/AlexanderLabWHOI/EUKulele/releases/tag/v2.0.1 https://pypi.org/project/EUKulele/2.0.1/ 

As of v2.0.1, the default is `.fasta` and the documentation has been adjusted accordingly; bioconda updates forthcoming (v2.0.1).
