### ISSUE TITLE
Setting customized evalue for filter_metric

### ISSUE THREAD

**Issue by lsjmouse** [AlexanderLabWHOI/EUKulele#48]
Hi,

I have a question about setting a customized evalue for filtering annotation hits. It writes in your software document that the parameter "--filter_metric" can be used to filter hits based on their quality prior to taxonomic estimation. But it didn’t say how to set the value instead of choosing from evalue, pid, or bitscore. For example in my case I only want to keep the taxonomy hits which above a certain e-value,  then how should I run it?

**Comment by akrinos** [comment]
@lsjmouse sorry I completely missed this comment! The parameter `--filter_metric` is used to select between evalue, pid, or bitscore, and within each of those the default behavior will be to use the highest value within each group. The percentage identity of the hit thereafter will be used to determine what level of taxonomy can be assigned to the hit. An e-value cutoff of 1e-5 and bitscore of 50 is used to select the initial hits, then the best hits of search results meeting that benchmark will be used for the selection variably depending on which filter metric you use. Thanks for using `EUKulele` and please follow up if you have additional questions or want to request a feature!
