### ISSUE TITLE
No samples found in sample directory with specified peptide extension.

### ISSUE THREAD

**Issue by shibormi** [AlexanderLabWHOI/EUKulele#59]
Running EUKulele with command line arguments, as no valid configuration file was provided.
Setting things up...
Could not successfully install all external dependent software.
Check DIAMOND, BLAST, BUSCO, and TransDecoder installation.
No samples found in sample directory with specified peptide extension.

**Comment by akrinos** [comment]
Hi @shibormi can you report your command and the result of listing the files in the specified sample directory?

**Comment by shibormi** [comment]
/usr/bin/time -v /storage/colddata/basesolve/tools/eukulele_2.0.7.sif EUKulele --sample_dir /storage/scratch2/NCGM-1741/Deliverables/assembly_fasta/assembly  --nucleotide_extension .fasta -m mags --perc_mem 64G --CPUs 32 -d /storage/colddata/basesolve/databases/EUKulele -o eukulele 2>&1 | tee Eukulele.log

**Comment by akrinos** [comment]
Hi @shibormi , what is the file extension of the samples in your sample directory?

**Comment by shibormi** [comment]
@akrinos the extention is .fna or .fasta

**Comment by akrinos** [comment]
hi @shibormi - could you try also specifying `--p_ext .fasta`, out of curiosity? uncertain exactly what is going on here

**Comment by akrinos** [comment]
Let me know if there were any updates!
