### ISSUE TITLE
EUKulele v2.0.7 fails taxonomy estimation step

### ISSUE THREAD

**Issue by danilodileo** [AlexanderLabWHOI/EUKulele#60]
Hi! I noticed that the new version of EUKulele fails in the taxonomy estimation step.

I ran this command on v2.0.7
`EUKulele -m mets --database gtdb --reference_dir eukulele -o megahit.prodigal --CPUs 2 -s contigs`

here how the output looks like:
`	transcript_name	classification_level	full_classification	classification	max_pid	counts	ambiguous	database
0	k141_0_1	class	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	82.0	0.0	0	
0	k141_1000_1	species	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	109.4	0.0	0	
0	k141_1000_2	genus	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	78.2	0.0	0	
0	k141_1001_2	species	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	104.4	0.0	0	
0	k141_1002_1	genus	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	99.8	0.0	0	
0	k141_1002_2	species	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	794.7	0.0	0	
0	k141_1002_3	species	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	438.0		0	GCF_000155975N1;GCF_018035235N1
0	k141_1003_1	genus	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	95.9	0.0	0	
0	k141_1003_2	species	MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict;MissingFromTaxDict	MissingFromTaxDict	96.7	0.0	0 ....`

I am pretty sure is the version since I tried the same command but with EUKulele v2.0.5 and it worked fine (got taxonomy annotation).

Any guess on what could be? 

I am using v2.0.5 at the moment but I just wanted to mention since the v2.0.7 is the new one.

Cheers!

**Comment by akrinos** [comment]
Fixed in release 2.0.9 https://github.com/AlexanderLabWHOI/EUKulele/releases/tag/2.0.9
