### ISSUE TITLE
Mamba install for eukulele=2.0.7 is problematic

### ISSUE THREAD

**Issue by g0ddengr** [AlexanderLabWHOI/EUKulele#63]
Hi,

I have been unable to install a working version of EUKulele/2.0.7 on our HPC. I created and activated a new environment, and then followed the mamba installation instructions here: https://eukulele.readthedocs.io/en/latest/install.html#installing-with-mamba

$ mamba install -c akrinos -c bioconda -c conda-forge EUKulele

This command runs successfully and without error. However, it yields an incomplete installation that lacks dependencies required to perform some EUKulele steps. For starters, I noted that the environment did not include zenodo-get, which was required to download the EukZoo db with the 'EUKulele download --database eukzoo' command. Once I install that with mamba, the database downloads. However, there are more problems. If I run the test data using the 'EUKulele --config curr_config.yaml' command, the pipeline runs but reports no BUSCO results. This is because more dependencies are missing: e.g., BUSCO and TransDecoder (and possibly AUGUSTUS too). BUSCO could not be installed with mamba at this point because of multiple conflicts, namely with biopython.

I removed the environment and started again, this time using a different creation strategy:

$ mamba create -p /eukulele/2.0.7 eukulele busco transdecoder zenodo_get

This approach was able to resolve conflicts and intstall an environment that I assumed included the required dependencies. However, when I run the same test described above 'EUKulele --config curr_config.yaml', the pipeline reports no BUSCO results. The log files indicate that the problem is due to an incompatibility between 
the installed busco=4.0.4 and biopython=1.78, which lacks bio.alphabet. I cannot downgrade biopython, and I cannot upgrade busco=4.0.6 without lots of conflicts. 

What do I need to change to yield a compatible and working environment? 

$ mamba list
# packages in environment at /apps/eukulele/2.0.7:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
augustus                  3.2.2                         0    bioconda
bamtools                  2.5.2                hdcf5f25_2    bioconda
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_33    conda-forge
bioconductor-seqlogo      1.52.0                    r36_0    bioconda
biopython                 1.78             py37h5e8e339_2    conda-forge
blast                     2.2.31                        1    bioconda
boost                     1.68.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
brotli-python             1.0.9            py37hd23a5d3_7    conda-forge
busco                     4.0.4                   pyr36_0    bioconda
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h43b0acd_1    conda-forge
chardet                   5.0.0            py37h89c1867_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2           py37h38fbfac_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dendropy                  4.5.1              pyh3252c3a_0    bioconda
diamond                   0.9.24               ha888412_1    bioconda
dnspython                 2.4.2              pyhd8ed1ab_0    conda-forge
eukulele                  2.0.7              pyh78b79e7_0    bioconda
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
expat                     2.6.1                h59595ed_0    conda-forge
findutils                 4.6.0             h166bdaf_1001    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gcc_impl_linux-64         7.5.0               habd7529_20    conda-forge
gcc_linux-64              7.5.0               h47867f9_33    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    7.5.0               h56cb351_20    conda-forge
gfortran_linux-64         7.5.0               h78c8a43_33    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
glib                      2.78.4               hfc55251_4    conda-forge
glib-tools                2.78.4               hfc55251_4    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gxx_impl_linux-64         7.5.0               hd0bb8aa_20    conda-forge
gxx_linux-64              7.5.0               h555fc39_33    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hmmer                     3.1b2                         3    bioconda
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  0.17.3             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_17    conda-forge
kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libexpat                  2.6.1                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     7.5.0               hda03d7c_20    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libglib                   2.78.4               hf2295e7_4    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  7.5.0               hb016644_20    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.4.0                h82bc61c_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib-base           3.3.3            py37h0c9df89_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.19.5           py37h3e96413_3    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pandas                    1.2.0            py37hdc94413_1    conda-forge
pango                     1.40.14           he7ab937_1005    conda-forge
pasta                     1.7.8            py37h8f50634_4    bioconda
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
perl-app-cpanminus        1.7047          pl5321hd8ed1ab_0    conda-forge
perl-business-isbn        3.007           pl5321hd8ed1ab_0    conda-forge
perl-business-isbn-data   20210112.006    pl5321hd8ed1ab_0    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-db-file              1.855           pl5321h779adbc_1    bioconda
perl-dbi                  1.643           pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-test-warnings        0.031           pl5321ha770c72_0    conda-forge
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-uri                  5.17            pl5321ha770c72_0    conda-forge
perl-yaml                 1.30            pl5321hdfd78af_0    bioconda
pillow                    9.2.0            py37h850a105_2    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prodigal                  2.6.3                h031d066_7    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pymongo                   4.3.2            py37hd23a5d3_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.12          hb7a2778_100_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-wget               3.2                        py_0    conda-forge
python_abi                3.7                     4_cp37m    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py37h540881e_4    conda-forge
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.2.1             r36hcfec24a_0    conda-forge
r-base                    3.6.1                h8900bf8_2    conda-forge
r-brio                    1.1.2             r36hcfec24a_0    conda-forge
r-callr                   3.7.0             r36hc72bb7e_0    conda-forge
r-cli                     2.5.0             r36hc72bb7e_0    conda-forge
r-colorspace              2.0_1             r36hcfec24a_0    conda-forge
r-crayon                  1.4.1             r36hc72bb7e_0    conda-forge
r-desc                    1.3.0             r36hc72bb7e_0    conda-forge
r-diffobj                 0.3.4             r36hcfec24a_0    conda-forge
r-digest                  0.6.27            r36h03ef668_0    conda-forge
r-ellipsis                0.3.2             r36hcfec24a_0    conda-forge
r-evaluate                0.14              r36h6115d3f_2    conda-forge
r-fansi                   0.4.2             r36hcfec24a_0    conda-forge
r-farver                  2.1.0             r36h03ef668_0    conda-forge
r-ggplot2                 3.3.3             r36hc72bb7e_0    conda-forge
r-glue                    1.4.2             r36hcfec24a_0    conda-forge
r-gtable                  0.3.0             r36h6115d3f_3    conda-forge
r-isoband                 0.2.4             r36h03ef668_0    conda-forge
r-jsonlite                1.7.2             r36hcfec24a_0    conda-forge
r-labeling                0.4.2             r36h142f84f_0    conda-forge
r-lattice                 0.20_44           r36hcfec24a_0    conda-forge
r-lifecycle               1.0.0             r36hc72bb7e_0    conda-forge
r-magrittr                2.0.1             r36hcfec24a_1    conda-forge
r-mass                    7.3_54            r36hcfec24a_0    conda-forge
r-matrix                  1.3_3             r36he454529_0    conda-forge
r-mgcv                    1.8_35            r36he454529_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1003    conda-forge
r-nlme                    3.1_150           r36h31ca83e_0    conda-forge
r-pillar                  1.6.1             r36hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_1    conda-forge
r-pkgload                 1.2.1             r36h03ef668_0    conda-forge
r-praise                  1.0.0           r36h6115d3f_1004    conda-forge
r-processx                3.5.2             r36hcfec24a_0    conda-forge
r-ps                      1.6.0             r36hcfec24a_0    conda-forge
r-r6                      2.5.0             r36hc72bb7e_0    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1003    conda-forge
r-rcpp                    1.0.6             r36h03ef668_0    conda-forge
r-rematch2                2.1.2             r36h6115d3f_1    conda-forge
r-rlang                   0.4.11            r36hcfec24a_0    conda-forge
r-rprojroot               2.0.2             r36hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r36hc72bb7e_0    conda-forge
r-scales                  1.1.1             r36h6115d3f_0    conda-forge
r-testthat                3.0.2             r36h03ef668_0    conda-forge
r-tibble                  3.1.2             r36hcfec24a_0    conda-forge
r-utf8                    1.2.1             r36hcfec24a_0    conda-forge
r-vctrs                   0.3.8             r36hcfec24a_1    conda-forge
r-viridislite             0.4.0             r36hc72bb7e_0    conda-forge
r-waldo                   0.2.5             r36hc72bb7e_0    conda-forge
r-withr                   2.4.2             r36hc72bb7e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.5.3            py37h8911b10_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
sepp                      4.5.1            py37h9ee0642_3    bioconda
setuptools                59.8.0           py37h89c1867_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.45.1               h2c6b66d_0    conda-forge
sysroot_linux-64          2.12                he073ed8_17    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tktable                   2.10                 h0c5db8f_5    conda-forge
tornado                   6.2              py37h540881e_0    conda-forge
transdecoder              5.7.1           pl5321hdfd78af_0    bioconda
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
ujson                     5.5.0            py37hd23a5d3_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zenodo_get                1.3.4              pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

Thank you in advance for your help.

Grant

**Comment by akrinos** [comment]
hey @g0ddengr , can you try removing `-c akrinos`?

**Comment by g0ddengr** [comment]
Hi @akrinos ,

This is what I get without the -c akrinos:

$ mamba install -c bioconda -c conda-forge EUKulele
...
Could not solve for environment specs
The following package could not be installed
└─ eukulele is not installable because it requires
   └─ biopython 1.78 , which conflicts with any installable versions previously reported.

**Comment by bgruening** [comment]
> conda create -n foo --dry-run -c conda-forge -c bioconda EUKulele

This works for me locally. Please make sure to always use `conda create`. Mamba is not needed anymore if you are using the latest conda version (mamba solver is now integrated into conda). Please also make sure conda-forge has the higher priority over bioconda.

**Comment by akrinos** [comment]
Hi @bgruening @g0ddengr - sorry for missing the reply in March, thank you @bgruening for sharing! @g0ddengr did you ever get the install to work?

**Comment by g0ddengr** [comment]
@bgruening and @akrinos. Thanks so much! I was able to make the installation without problems.
