### ISSUE TITLE
EUKulele quits w/o any explicit error

### ISSUE THREAD

**Issue by rustem-musaev** [AlexanderLabWHOI/EUKulele#68]
Hello!

I run the following command:

`EUKulele --sample_dir . -m mags`

With the sample directory containing three files: "prot_seq.faa", "mag.fasta" and a GTF file (which isn't used in this case anyway), and EUKulele seems to abruptly stop as soon as it proceeds to the taxonomic visualization step:

```
...
Aligning sample prot_seq...
Diamond process exited for sample prot_seq.
Performing taxonomic estimation steps...
Performing taxonomic visualization steps...
```

And that's it. Then in the output folder, I only see a few subfolders ("taxonomy_estimation" with a table with classified proteins, "log", "mags_full") and "README_DB.txt". I should definitely have more than that according to the documentation, at least a consensus taxonomy file. I have tried to reinstall EUKulele and the environment, BUSCO, etc., but nothing has worked so far. What should I do? Thanks!

**Comment by akrinos** [comment]
@rustem-musaev thank you for your interest in `EUKulele`! Sorry to hear that your are having some issues with the tool. Do you end up with log files in the output folder inside the `log` subfolder? If so, what do those log files contain? Thanks!

**Comment by rustem-musaev** [comment]
Yes, I do! There's 6 pairs of "err" and "out" files: "alignment_err.log",  "dependency_err.txt",  "full_diamond_align_prot_seq.err", "proteintab.err",  "tax_est_prot_seq.err",  "tax_vis.err", "alignment_out.log",  "dependency_log.txt",  "full_diamond_align_prot_seq.log",  "proteintab.log",  "tax_est_prot_seq.out", "tax_vis.out".

I reckon the "tax_vis" files are the most relevant in this case (the others seem fine anyway). "tax_vis.err" is empty, and "tax_vis.out" reads, `"One of the files, mag.fasta, in the sample directory did not complete successfully."` My MAGs are quite short (few have contigs greater than 50 kbps) and contain soft-masked sequences, but they should still be fine: I feel I've worked with much more 'finicky' metagenomic tools to get this far.

**Comment by akrinos** [comment]
Hi @rustem-musaev - sorry for the clearly opaque errors! Generally I would expect for that error in the visualization step to indicate that that particular file did not complete successfully in the previous step (taxonomy estimation). Is there an output file corresponding to that input present in the taxonomy estimation folder? Strangely, "prot_seq" appears to be the only file with ssociated log files in previous steps, not "mag.fasta".

**Comment by rustem-musaev** [comment]
@akrinos Both of the "tax_est" log files are empty. Indeed, it's strange that "mag.fasta" is the cause of the problem, I thought the protein file is the main input. Yes, there is this "prot_seq-estimated-taxonomy.out" in the output folder, and as I said in the first comment, with taxa assigned only to individual proteins, but this is the only file there and there's no consensus taxonomy file that I'm looking for.

**Comment by akrinos** [comment]
@rustem-musaev is `mag.fasta` also found in the input directory, but you intend for `EUKulele` to be run on proteins?

**Comment by akrinos** [comment]
@rustem-musaev - this is a bug! essentially, you're running in MAG mode & only protein files are allowed for MAG mode...yet, in the visualization step, both files that fit the specified protein extension and nucleotide extension will be checked for taxonomy estimation output. In the short run, you can fix this via adding to your command `--n_ext <anything-but-fasta>`, because then the default `.fasta` extension that also belongs to your `mag.fasta` file in the sample directory folder will not be treated as a valid input. This fix will be included in the imminent new `EUKulele` version, as `EUKulele` should not allow nucleotide files to be used in any step when using MAG mode. Thank you!

**Comment by rustem-musaev** [comment]
@akrinos I see..Yes, it's finally working now, thank you very much!

**Comment by akrinos** [comment]
@rustem-musaev great, so glad that pushed things forward! Closing this issue but I will mention this issue when I push the new `EUKulele` version. Thanks so much for using `EUKulele` and please feel free to open additional issues if you have further problems!
